java_library (
    name = "greeter",
    srcs = glob(["src/main/java/com/example/bazelspringBoot/*.java"]),
    visibility = ["//api:__pkg__"],
    deps = [
    '@maven//:org_springframework_boot_spring_boot',
    '@maven//:org_springframework_boot_spring_boot_autoconfigure',
    '@maven//:org_springframework_boot_spring_boot_starter_web',
    '@maven//:org_springframework_spring_web',
    '@maven//:org_springframework_spring_context'
    ]
)